Added .exe and .sh handling to path
If command is not found, check if the command should have been .exe and
.sh

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -43,6 +43,31 @@ function update-env-forwarding
     fi
 }
 
+function command_not_found_handle {
+	# check because c-n-f could've been removed in the meantime
+
+	if [ `which "$1.exe"` ]; then
+		echo "Found alternative $1.exe, executing"
+		exe="$1.exe"
+		shift;
+		$exe "$@"
+	elif [ `which "$1.sh"` ]; then
+		echo "Found alternative $1.sh, executing"
+		script="$1.sh"
+		shift;
+		$script "$@"
+	elif [ -x /usr/lib/command-not-found ]; then
+		/usr/lib/command-not-found -- "$1"
+		return $?
+	elif [ -x /usr/share/command-not-found/command-not-found ]; then
+		/usr/share/command-not-found/command-not-found -- "$1"
+		return $?
+	else
+		printf "%s: command not found\n" "$1" >&2
+		return 127
+	fi
+}
+
 #Setting up editors
 export VISUAL=/usr/bin/vim
 export EDITOR=/usr/bin/vim
